[[catalogs]]
catalog_id = "$CATALOG_ID_0"
catalog_name = "$CATALOG_NAME_0"
catalog_path = "$CATALOG_PATH_0"
catalog_dir = "$CATALOG_DIR_0"
catalog_include_glob_pattern = $CATALOG_INCLUDE_GLOB_PATTERN_0
catalog_scm_clone_cmd = "$CATALOG_GIT_CLONE_0"
catalog_scm_pull_cmd = "$CATALOG_GIT_PULL_0"
catalog_scm_clone = "$CATALOG_CLONE_0"
catalog_http_base_uri = "$STASH_CONFIG_BASE_URI_0"

[[catalogs]]
catalog_id = "$CATALOG_ID_1"
catalog_name = "$CATALOG_NAME_1"
catalog_path = "$CATALOG_PATH_1"
catalog_dir = "$CATALOG_DIR_1"
catalog_include_glob_pattern = $CATALOG_INCLUDE_GLOB_PATTERN_1
catalog_scm_clone_cmd = "$CATALOG_GIT_CLONE_1"
catalog_scm_pull_cmd = "$CATALOG_GIT_PULL_1"
catalog_scm_clone = "$CATALOG_CLONE_1"
catalog_http_base_uri = "$STASH_CONFIG_BASE_URI_1"

[[catalogs]]
catalog_id = "$CATALOG_ID_2"
catalog_name = "$CATALOG_NAME_2"
catalog_path = "$CATALOG_PATH_2"
catalog_dir = "$CATALOG_DIR_2"
catalog_include_glob_pattern = $CATALOG_INCLUDE_GLOB_PATTERN_2
catalog_scm_clone_cmd = "$CATALOG_GIT_CLONE_2"
catalog_scm_pull_cmd = "$CATALOG_GIT_PULL_2"
catalog_scm_clone = "$CATALOG_CLONE_2"
catalog_http_base_uri = "$STASH_CONFIG_BASE_URI_2"

[stash_config]
base_uri = "$STASH_CONFIG_BASE_URI"
access_token = "$STASH_CONFIG_ACCESS_TOKEN"

[search]
index_path="$SEARCH_CONFIG_INDEX_DIR"

[server]
bind_adress = "$SERVER_BIND_ADRESS"
static_resources_path = "$SERVER_STATIC_RESOURCES_PATH"

[database]
rusqlite_path = "$DATABASE_RUSQLITE_PATH"

[domain_repo_type]
# can be YamlBasedDomainRepo or DbBasedDomainRepo
domain_impl = "$DOMAIN_REPO_TYPE_DOMAIN_IMPL"
domain_catalog_path = "$DOMAIN_REPO_TYPE_DOMAIN_CATALOG_PATH"

[systems_and_layers]
systems_catalog_path = "$SYSTEMS_CATALOG_PATH"

[ui_config]
api_doc_url = "$API_DOC_URL"
pact_url = "$PACT_URL"
stash_base_url = "$STASH_BASE_URL"
beta = $BETA