name: Rust

on: [push]

jobs:
  build: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: clean
        run: cargo clean
      - name: Build
        run: cargo build --verbose  
        env:
          RUST_BACKTRACE: 1
      - name: Run tests
        run: cargo test --verbose
        env:
          RUST_BACKTRACE: 1

  publish_metrics:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate and publish code coverage
      #This is a crappy work around. Got issues as tarpaulin seems to be running `cargo test -- --test-threads 1
      # which seems to not work w/ the used version of cucumber-rust. 
      #Changhing harness = true work around the pb...
      #Also seems like cucumber tests are part of coverage measures (which is nice)
        run: |
          cargo install cargo-tarpaulin
          sed -i 's/harness = false/harness = true/g' `pwd`/adr_core_local_impl/Cargo.toml
          cargo tarpaulin --release --out Lcov --coveralls cWQm7CpdlatuS7Ws7pZPVwCYye0l3wPoL